# Generated by Django 3.2.20 on 2023-09-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gateway',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Stripe'), (2, 'Manual'), (3, 'Crypto')], default=0),
        ),
    ]
