# Generated by Django 3.2.20 on 2023-10-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='instance',
            field=models.IntegerField(choices=[(0, 'Product'), (1, 'Service')], default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Suspended'), (2, 'Active')], default=0),
        ),
        migrations.AddField(
            model_name='like',
            name='instance',
            field=models.IntegerField(choices=[(0, 'Product'), (1, 'Service')], default=0),
        ),
        migrations.AddField(
            model_name='like',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Suspended'), (2, 'Active')], default=0),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
