# Generated by Django 3.2.20 on 2023-08-31 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20230830_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='type',
            field=models.IntegerField(choices=[(0, 'Individual'), (1, 'Business'), (2, 'Developer')], default=0),
        ),
    ]
