# Generated by Django 3.2.20 on 2023-10-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20231009_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='instance',
            field=models.IntegerField(choices=[(0, 'Product'), (1, 'Service')], default=0),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
