# Generated by Django 3.2.20 on 2023-09-29 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_alter_like_liker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_transactions',
        ),
    ]
