# Generated by Django 3.2.20 on 2023-08-30 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category_name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='download',
            options={'ordering': ['product', 'service']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['product', 'service']},
        ),
        migrations.AlterField(
            model_name='download',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_downloads', to='product_service.product'),
        ),
        migrations.AlterField(
            model_name='download',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_downloads', to='product_service.service'),
        ),
        migrations.AlterField(
            model_name='download',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Suspended'), (2, 'Active')], default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Suspended'), (2, 'Active')], default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Ownership'), (2, 'License')], default=1),
        ),
        migrations.AlterField(
            model_name='service',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Suspended'), (2, 'Active')], default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Ownership'), (2, 'License')], default=1),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='gateway',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Stripe'), (2, 'Manual'), (3, 'Crypto')], default=0),
        ),
    ]
