# Generated by Django 3.2.20 on 2023-08-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
