# Generated by Django 3.2.20 on 2023-08-30 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_service', '0002_auto_20230830_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_downloads', to='product_service.product'),
        ),
        migrations.AlterField(
            model_name='download',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_downloads', to='product_service.service'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_service.product'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_service.service'),
        ),
    ]
