# Generated by Django 3.2.20 on 2023-08-30 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_service', '0003_alter_download_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_downloads', to='product_service.product'),
        ),
        migrations.AlterField(
            model_name='download',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_downloads', to='product_service.service'),
        ),
    ]
