# Generated by Django 3.2.20 on 2023-09-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_service', '0004_auto_20230903_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(choices=[(0, 'HTML'), (1, 'CSS'), (2, 'JS'), (3, 'PY'), (4, 'MD')])),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.ManyToManyField(related_name='code_type', to='product_service.CodeType'),
        ),
    ]
