# Generated by Django 3.2.20 on 2023-09-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_service', '0007_alter_codetype_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codetype',
            name='code',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
