# Generated by Django 3.2.20 on 2023-09-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_service', '0008_alter_codetype_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name_plural': 'ServiceTypes',
                'ordering': ['service'],
            },
        ),
        migrations.AlterModelOptions(
            name='codetype',
            options={'ordering': ['code'], 'verbose_name_plural': 'CodeTypes'},
        ),
        migrations.AddField(
            model_name='product',
            name='service',
            field=models.ManyToManyField(related_name='service_type', to='product_service.ServiceType'),
        ),
    ]
