# Generated by Django 3.2.20 on 2023-09-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_service', '0010_product_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='docs',
            field=models.URLField(blank=True, max_length=1024, null=True, unique=True),
        ),
    ]
