# Generated by Django 3.2.20 on 2023-09-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_service', '0011_product_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='code',
            field=models.ManyToManyField(related_name='code_type_service', to='product_service.CodeType'),
        ),
        migrations.AddField(
            model_name='service',
            name='docs',
            field=models.URLField(blank=True, max_length=1024, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='service',
            name='preview',
            field=models.URLField(blank=True, max_length=1024, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service',
            field=models.ManyToManyField(related_name='on_service_type', to='product_service.ServiceType'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
