# Generated by Django 3.2.20 on 2023-09-10 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_service', '0012_auto_20230904_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='instance',
            field=models.IntegerField(choices=[(0, 'Product'), (1, 'Service')], default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='instance',
            field=models.IntegerField(choices=[(0, 'Product'), (1, 'Service')], default=1),
        ),
    ]
