# Generated by Django 3.2.20 on 2023-09-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_service', '0014_auto_20230911_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.IntegerField(choices=[(0, 'NA'), (1, 'Ownership'), (2, 'License')], default=1),
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.IntegerField(choices=[(0, 'NA'), (1, 'Ownership'), (2, 'License')], default=1),
        ),
    ]
