# Generated by Django 3.2.20 on 2023-09-29 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_service', '0015_auto_20230914_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='transactions',
        ),
        migrations.RemoveField(
            model_name='service',
            name='transactions',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
