# Generated by Django 3.2.20 on 2023-09-30 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_gateway'),
        ('product_service', '0016_auto_20230929_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='product_orders', to='checkout.Order'),
        ),
    ]
