# Generated by Django 3.2.20 on 2023-09-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_service', '0017_product_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='download',
            name='file_url',
        ),
        migrations.AddField(
            model_name='download',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='downloads/'),
        ),
    ]
