# Generated by Django 3.2.20 on 2023-09-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_service', '0018_auto_20230930_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='file_name',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
